package com.lifelinkai.backend.model;

public enum NotificationType {
    SOS_CREATED,
    AMBULANCE_ASSIGNED,
    AMBULANCE_APPROACHING,
    AMBULANCE_ARRIVED,
    PATIENT_PICKED_UP,
    HOSPITAL_ARRIVAL,
    HOSPITAL_ACCEPTED,
    HOSPITAL_REJECTED,
    EMERGENCY_STATUS_UPDATED,
    EMERGENCY_COMPLETED
}
